Repository CS-Challenge/ALGORITHM-Challenge, pull requests merged in 2023-06, with the labels that each got.

#2 김유정: 뉴스클러스터링 문제풀이(23.06.12)
  week1/뉴스클러스터링/김유정_뉴스클러스터링.py
Labels: 진행중

#3 Yooyeon
  week1/뉴스클러스터링/황유연_뉴스클러스터링.py
Labels: 완료

#4 장세웅: 뉴스클러스터링(23.06.12)
  week1/뉴스클러스터링/장세웅_뉴스클러스터링.java
Labels: 완료

#6 김유정: 광고삽입 문제풀이(23.06.13)
  week2/광고삽입/김유정_광고삽입.java
Labels: 진행중

#7 황유연: 광고삽입(23.06.13)
  week1/광고삽입/황유연_광고삽입.py
Labels: 완료

#8 장세웅: 광고삽입(23.06.13)
  week1/광고삽입/장세웅_광고삽입.java
Labels: 완료

#11 황유연: 숫자야구 문제풀이(23.06.14)
  week1/숫자야구/황유연_숫자야구.py
Labels: 완료

#12 장세웅: 숫자야구(23.06.14)
  week1/숫자야구/장세웅_숫자야구.java
Labels: 완료

#14 황유연: 전력망 둘로 나누기 문제풀이(23.06.15)
  week1/전력망 둘로 나누기/황유연_전력망 둘로 나누기.py
Labels: 완료

#15 Kimyoujung
  .github/pull_request_template.md
  week1/전력망 둘로 나누기/김유정_전력망_둘로_나누기.java
Labels: 완료

#17 장세웅: 전력망 둘로 나누기(23.06.15)
  week1/전력망 둘로 나누기/장세웅_전력망_둘로_나누기.java
Labels: 완료

#20 황유연: 빙고 문제풀이(23.06.19)
  week1/빙고/황유연_빙고.py
Labels: 완료

#21 김유정: 빙고(23.06.19)
  week2/빙고/김유정_빙고.java
Labels: 완료

#22 장세웅: 빙고(23.06.19)
  week2/빙고/장세웅_빙고.java
Labels: 완료

#24 황유연: 합승 택시 요금 문제풀이(23.06.20)
  week2/빙고/황유연_빙고.py
  week2/합승_택시_요금/황유연_합승_택시_요금.py
Labels: 완료

#25 김유정: 합승택시요금 문제풀이(23.06.20)
  week2/합승_택시_요금/김유정_합승택시요금.java
Labels: 진행중

#29 황유연: 게임 맵 최단거리 문제풀이(23.06.21)
  week2/게임_맵_최단거리/황유연_게임_맵_최단거리.java
Labels: 완료

#31 장세웅 : 합승 택시 요금, 게임 맵 최단거리(23.06.21)
  week2/게임_맵_최단거리/장세웅_게임_맵_최단거리.java
  week2/합승_택시_요금/장세웅_합승_택시_요금.java
Labels: 완료

#33 황유연: 보석쇼핑 문제풀이(23.06.22)
  week2/보석쇼핑/황유연_보석쇼핑.py
Labels: 진행중

#36 장세웅 보석쇼핑 (23.06.23)
  week2/보석쇼핑/장세웅_보석_쇼핑.java
Labels: 다시 풀어볼 문제

#40 김유정: 단어 변환 문제풀이(23.06.27)
  week3/단어_변환/김유정_단어_변환.java
Labels: 완료

#41 장세웅: 미로 탈출 명령어, 단어 변환(23.06.27)
  week3/단어_변환/장세웅_단어_변환.java
  week3/미로_탈출_명령어/장세웅_미로_탈출_명령어.java
Labels: 다시 풀어볼 문제, 완료

#42 황유연: 미로탈출 명령어, 풍선 터트리기 문제풀이(23.06.27)
  week3/미로_탈출_명령어/황유연_미로_탈출_명령어.py
  week3/풍선_터트리기/황유연_풍선_터트리기.py
Labels: 진행중

#44 황유연: 단어 변환 문제풀이(23.06.28)
  week3/단어_변환/황유연_단어_변환.py
Labels: 완료

#45 김유정: 풍선 터트리기 문제 풀이(23.06.28)
  week3/단어_변환/김유정_단어_변환.java
  week3/풍선_터트리기/김유정_풍선_터트리기.java
Labels: 완료

#47 황유연: 트럭 문제풀이(23.06.29)
  week3/트럭/황유연_트럭.py
  week3/풍선_터트리기/황유연_풍선_터트리기.py
Labels: 완료

#48 김유정: 트럭 문제풀이(23.06.29)
  week3/트럭/김유정_트럭.java
Labels: 완료
